export const INNER_LOADER = "INNER_LOADER";
export const CLEAR_INNER_LOADER = "INNER_LOADER";
export const MAIN_LOADER = "MAIN_LOADER";
export const CLEAR_MAIN_LOADER = "CLEAR_MAIN_LOADER";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

export const ALL_STUDENT = "ALL_STUDENT";
export const CLEAR_ALL_STUDENT = "CLEAR_ALL_STUDENT";

export const ALL_COURSES="ALL_COURSES"
export const CLEAR_ALL_COURSES="CLEAR_ALL_COURSES"
export const ALL_FILTERED_COURSES="ALL_FILTERD_COURSES";

export const ALL_BATCHES="ALL_BATCHES"
export const CLEAR_ALL_BATCHES="CLEAR_ALL_BATCHES"
export const ALL_FILTERED_BATCHES="ALL_FILTERED_BATCHES";

